#!/usr/bin/env ruby

site 'https://supermarket.getchef.com/api/v1'

cookbook 'sprout-rbenv',
  :github => 'pivotal-sprout/sprout-rbenv'

cookbook 'sprout-ruby',
  :github => 'pivotal-sprout/sprout-ruby'

cookbook 'sprout-git',
  :github => 'pivotal-sprout/sprout-git'

cookbook 'sprout-base',
  :github => 'pivotal-sprout/sprout-base'

cookbook 'rs-sprout-base',
  :path => './site-cookbooks/rs-sprout-base'

cookbook 'sprout-osx-apps',
  :github => 'pivotal-sprout/sprout-osx-apps'

cookbook 'sprout-osx-settings',
  :github => 'pivotal-sprout/sprout-osx-settings'

cookbook 'osx',
  :github => 'pivotal-sprout/osx'

cookbook 'sprout-homebrew',
  :github => 'pivotal-sprout/sprout-homebrew'

cookbook 'rs-sprout-homebrew',
  :path => './site-cookbooks/rs-sprout-homebrew'

cookbook 'sprout-terminal',
  :github => 'pivotal-sprout/sprout-terminal'

cookbook 'sprout-ssh',
  :github => 'pivotal-sprout/sprout-ssh'

cookbook 'sprout-jetbrains-editors',
  :github => 'pivotal-sprout/sprout-jetbrains-editors'

cookbook 'rs-osx-settings',
  :path => './site-cookbooks/rs-osx-settings'
