name             'rs-sprout-homebrew'
maintainer       'RealScout'
maintainer_email 'chris@realscout.com'
license          'MIT'
description      'Recipes to configure various aspects of homebrew'
long_description 'hi'
version          '0.1.0'
supports         'mac_os_x'
depends          'sprout-base'
depends          'homebrew'
depends          'osx'

